-- Current schema snapshot, generated by hand from database/migrations/.
-- This file is documentation, not something the application reads —
-- MigrationRunner applies the migrations directly. Regenerate this
-- comment-for-comment whenever a migration is added, so a reader never
-- has to replay migrations in their head to know what the database
-- currently looks like.
--
-- Version: 1 (database/migrations/0001_init.sql)

CREATE TABLE schema_migrations (
  version    INTEGER PRIMARY KEY,
  name       TEXT NOT NULL,
  applied_at INTEGER NOT NULL
);
-- Bookkeeping only, created by MigrationRunner itself, not by a migration
-- file — a migration can't record its own application before it exists.

CREATE TABLE world_events (
  sequence  INTEGER PRIMARY KEY,
  id        TEXT NOT NULL UNIQUE,
  type      TEXT NOT NULL,
  timestamp INTEGER NOT NULL,
  payload   TEXT NOT NULL
);

CREATE INDEX idx_world_events_type ON world_events(type);
CREATE INDEX idx_world_events_timestamp ON world_events(timestamp);

-- Deliberately absent: `entities`, `relationships`, `conversations`,
-- `messages`, `observations`, `insights`, `suggestions` tables. All of
-- these are Entities or Relationships in the canonical model (see
-- src/world/canonical/EntityTypes.ts — Conversation, Message, Insight,
-- Observation, and Suggestion are all registered entity types) and are
-- therefore persisted as ENTITY_CREATED / RELATIONSHIP_CREATED events in
-- `world_events`, not as their own tables. See database/migrations/0001_init.sql
-- for why: the event log is Phase 4's single authoritative store, and
-- current state is always a rebuildable projection of it, never a second
-- table that could drift from it.
